services:
  frontend:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:${APP_BIND_PORT:-18081}:80"
    networks:
      - default
      - backend
      - face_tracking

networks:
  default: {}
  backend:
    external: true
    name: backend_default
  face_tracking:
    external: true
    name: face-tracking_default
